// Auto-generated by tools/generate_consumables_catalog.mjs
// Do not edit manually.

export const GENERATED_CONSUMABLE_CATALOG = [
  {
    "consumableId": "healing_potion",
    "itemCode": "consumable_healing_potion",
    "displayName": "Healing Potion",
    "type": "potion",
    "family": "recovery",
    "rarity": "common",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "healing",
    "distillTier": "base",
    "legacyReplaces": [
      "Field Tonic",
      "Greater Healing Potion",
      "Vigorous Restorative"
    ],
    "iconKey": "consumable_healing_potion",
    "description": "Restore health instantly between encounters",
    "effects": [
      {
        "type": "restore_health_pct_max",
        "value": 5
      }
    ]
  },
  {
    "consumableId": "second_wind_potion",
    "itemCode": "consumable_second_wind_potion",
    "displayName": "Second Wind Potion",
    "type": "potion",
    "family": "stamina",
    "rarity": "common",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "second_wind",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_second_wind_potion",
    "description": "Restore stamina instantly before the next outing",
    "effects": [
      {
        "type": "restore_stamina_pct_max",
        "value": 5
      }
    ]
  },
  {
    "consumableId": "wardens_tonic",
    "itemCode": "consumable_wardens_tonic",
    "displayName": "Warden's Tonic",
    "type": "tonic",
    "family": "defense",
    "rarity": "common",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardens",
    "distillTier": "base",
    "legacyReplaces": [
      "Warden's Draft"
    ],
    "iconKey": "consumable_wardens_tonic",
    "description": "Steady the player for the next three encounters",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "hunters_tonic",
    "itemCode": "consumable_hunters_tonic",
    "displayName": "Hunter's Tonic",
    "type": "tonic",
    "family": "precision",
    "rarity": "common",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hunters",
    "distillTier": "base",
    "legacyReplaces": [
      "Hunter's Draft"
    ],
    "iconKey": "consumable_hunters_tonic",
    "description": "Tighten aim and finishing reliability for the next three encounters",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "emberwake_tonic",
    "itemCode": "consumable_emberwake_tonic",
    "displayName": "Emberwake Tonic",
    "type": "tonic",
    "family": "offense",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "emberwake",
    "distillTier": "base",
    "legacyReplaces": [
      "Emberwake Draft"
    ],
    "iconKey": "consumable_emberwake_tonic",
    "description": "Push damage output for aggressive contract windows",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1500
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "berserkers_tonic",
    "itemCode": "consumable_berserkers_tonic",
    "displayName": "Berserker's Tonic",
    "type": "tonic",
    "family": "frenzy",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "berserkers",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_berserkers_tonic",
    "description": "Drive a short burst of reckless tempo and finishing pressure",
    "effects": [
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "bulwark_tonic",
    "itemCode": "consumable_bulwark_tonic",
    "displayName": "Bulwark Tonic",
    "type": "tonic",
    "family": "bulwark",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "bulwark",
    "distillTier": "base",
    "legacyReplaces": [
      "Bulwark Distillate"
    ],
    "iconKey": "consumable_bulwark_tonic",
    "description": "Trade cost for a heavier defensive push",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1800
      },
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "wardwash_tonic",
    "itemCode": "consumable_wardwash_tonic",
    "displayName": "Wardwash Tonic",
    "type": "tonic",
    "family": "warding",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardwash",
    "distillTier": "base",
    "legacyReplaces": [
      "Wardwash Tonic"
    ],
    "iconKey": "consumable_wardwash_tonic",
    "description": "Prepare for hostile conditions and hex pressure",
    "effects": [
      {
        "type": "affliction_resist_bps",
        "value": 3000
      },
      {
        "type": "stat_bps",
        "target": "magicDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "hexcleanse_tonic",
    "itemCode": "consumable_hexcleanse_tonic",
    "displayName": "Hexcleanse Tonic",
    "type": "tonic",
    "family": "cleansing",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hexcleanse",
    "distillTier": "base",
    "legacyReplaces": [
      "Hexcleanse Phial"
    ],
    "iconKey": "consumable_hexcleanse_tonic",
    "description": "Break one lingering affliction and harden against the next wave",
    "effects": [
      {
        "type": "clear_affliction",
        "target": "single",
        "value": 1
      },
      {
        "type": "affliction_resist_bps",
        "value": 5000
      }
    ]
  },
  {
    "consumableId": "ravagers_tonic",
    "itemCode": "consumable_ravagers_tonic",
    "displayName": "Ravager's Tonic",
    "type": "tonic",
    "family": "momentum",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "ravagers",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_ravagers_tonic",
    "description": "Lean into hard openings with stronger damage and faster tempo",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_flat",
        "target": "initiative",
        "value": 6
      }
    ]
  },
  {
    "consumableId": "sunspike_elixir",
    "itemCode": "consumable_sunspike_elixir",
    "displayName": "Sunspike Elixir",
    "type": "elixir",
    "family": "offense",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "sunspike",
    "distillTier": "base",
    "legacyReplaces": [
      "Sunspike Elixir"
    ],
    "iconKey": "consumable_sunspike_elixir",
    "description": "An extended offensive brew for long damage-focused sessions",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "graveward_elixir",
    "itemCode": "consumable_graveward_elixir",
    "displayName": "Graveward Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "graveward",
    "distillTier": "base",
    "legacyReplaces": [
      "Graveward Elixir"
    ],
    "iconKey": "consumable_graveward_elixir",
    "description": "An extended defensive brew for attrition-heavy sessions",
    "effects": [
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "wardens_challenge_elixir",
    "itemCode": "consumable_wardens_challenge_elixir",
    "displayName": "Warden's Challenge Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "wardens_challenge",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_wardens_challenge_elixir",
    "description": "Call hostile focus and hold the line for the next encounters",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": 1800
      }
    ]
  },
  {
    "consumableId": "shadowveil_elixir",
    "itemCode": "consumable_shadowveil_elixir",
    "displayName": "Shadowveil Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "shadowveil",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_shadowveil_elixir",
    "description": "Suppress combat presence to keep pressure off fragile damage dealers",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": -1800
      }
    ]
  },
  {
    "consumableId": "deadeye_elixir",
    "itemCode": "consumable_deadeye_elixir",
    "displayName": "Deadeye Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "deadeye",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_deadeye_elixir",
    "description": "Maintain cleaner aim and higher critical conversion over a long session",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "travelers_elixir",
    "itemCode": "consumable_travelers_elixir",
    "displayName": "Traveler's Elixir",
    "type": "elixir",
    "family": "travel",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "travelers",
    "distillTier": "base",
    "legacyReplaces": [
      "Traveler's Distillate"
    ],
    "iconKey": "consumable_travelers_elixir",
    "description": "Trim wasted movement and stretch contract stamina over a session",
    "effects": [
      {
        "type": "contract_travel_duration_percent",
        "value": 20
      },
      {
        "type": "contract_stamina_cost_percent",
        "value": 10
      }
    ]
  },
  {
    "consumableId": "contractors_resolve_elixir",
    "itemCode": "consumable_contractors_resolve_elixir",
    "displayName": "Contractor's Resolve Elixir",
    "type": "elixir",
    "family": "wealth",
    "rarity": "uncommon",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "contractors_resolve",
    "distillTier": "base",
    "legacyReplaces": [
      "Contractor's Resolve"
    ],
    "iconKey": "consumable_contractors_resolve_elixir",
    "description": "Increase contract payout efficiency for a planned money run",
    "effects": [
      {
        "type": "contract_ducats_percent",
        "value": 15
      },
      {
        "type": "contract_item_drop_bps",
        "value": 100
      }
    ]
  },
  {
    "consumableId": "chroniclers_elixir",
    "itemCode": "consumable_chroniclers_elixir",
    "displayName": "Chronicler's Elixir",
    "type": "elixir",
    "family": "experience",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "chroniclers",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_chroniclers_elixir",
    "description": "A rare study elixir reserved for focused progression sessions",
    "effects": [
      {
        "type": "contract_xp_percent",
        "value": 20
      }
    ]
  },
  {
    "consumableId": "warcallers_elixir",
    "itemCode": "consumable_warcallers_elixir",
    "displayName": "Warcaller's Elixir",
    "type": "elixir",
    "family": "frenzy",
    "rarity": "rare",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "warcallers",
    "distillTier": "base",
    "legacyReplaces": [],
    "iconKey": "consumable_warcallers_elixir",
    "description": "Keep sustained pressure high through longer offensive sessions",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 800
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 600
      }
    ]
  },
  {
    "consumableId": "healing_potion",
    "itemCode": "consumable_healing_potion_d1",
    "displayName": "Potent Healing Potion",
    "type": "potion",
    "family": "recovery",
    "rarity": "uncommon",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "healing",
    "distillTier": "d1",
    "legacyReplaces": [
      "Field Tonic",
      "Greater Healing Potion",
      "Vigorous Restorative"
    ],
    "iconKey": "consumable_healing_potion",
    "description": "Potent refinement of Healing Potion.",
    "effects": [
      {
        "type": "restore_health_pct_max",
        "value": 15
      }
    ]
  },
  {
    "consumableId": "healing_potion",
    "itemCode": "consumable_healing_potion_d2",
    "displayName": "Mythic Healing Potion",
    "type": "potion",
    "family": "recovery",
    "rarity": "rare",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "healing",
    "distillTier": "d2",
    "legacyReplaces": [
      "Field Tonic",
      "Greater Healing Potion",
      "Vigorous Restorative"
    ],
    "iconKey": "consumable_healing_potion",
    "description": "Mythic refinement of Healing Potion.",
    "effects": [
      {
        "type": "restore_health_pct_max",
        "value": 50
      }
    ]
  },
  {
    "consumableId": "second_wind_potion",
    "itemCode": "consumable_second_wind_potion_d1",
    "displayName": "Potent Second Wind Potion",
    "type": "potion",
    "family": "stamina",
    "rarity": "uncommon",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "second_wind",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_second_wind_potion",
    "description": "Potent refinement of Second Wind Potion.",
    "effects": [
      {
        "type": "restore_stamina_pct_max",
        "value": 15
      }
    ]
  },
  {
    "consumableId": "second_wind_potion",
    "itemCode": "consumable_second_wind_potion_d2",
    "displayName": "Mythic Second Wind Potion",
    "type": "potion",
    "family": "stamina",
    "rarity": "rare",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "instant",
    "durationValue": 0,
    "distillGroup": "second_wind",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_second_wind_potion",
    "description": "Mythic refinement of Second Wind Potion.",
    "effects": [
      {
        "type": "restore_stamina_pct_max",
        "value": 50
      }
    ]
  },
  {
    "consumableId": "wardens_tonic",
    "itemCode": "consumable_wardens_tonic_d1",
    "displayName": "Potent Warden's Tonic",
    "type": "tonic",
    "family": "defense",
    "rarity": "uncommon",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardens",
    "distillTier": "d1",
    "legacyReplaces": [
      "Warden's Draft"
    ],
    "iconKey": "consumable_wardens_tonic",
    "description": "Potent refinement of Warden's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "wardens_tonic",
    "itemCode": "consumable_wardens_tonic_d2",
    "displayName": "Mythic Warden's Tonic",
    "type": "tonic",
    "family": "defense",
    "rarity": "rare",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardens",
    "distillTier": "d2",
    "legacyReplaces": [
      "Warden's Draft"
    ],
    "iconKey": "consumable_wardens_tonic",
    "description": "Mythic refinement of Warden's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "hunters_tonic",
    "itemCode": "consumable_hunters_tonic_d1",
    "displayName": "Potent Hunter's Tonic",
    "type": "tonic",
    "family": "precision",
    "rarity": "uncommon",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hunters",
    "distillTier": "d1",
    "legacyReplaces": [
      "Hunter's Draft"
    ],
    "iconKey": "consumable_hunters_tonic",
    "description": "Potent refinement of Hunter's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "hunters_tonic",
    "itemCode": "consumable_hunters_tonic_d2",
    "displayName": "Mythic Hunter's Tonic",
    "type": "tonic",
    "family": "precision",
    "rarity": "rare",
    "unlockBand": "easy",
    "craftingTier": "t1",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hunters",
    "distillTier": "d2",
    "legacyReplaces": [
      "Hunter's Draft"
    ],
    "iconKey": "consumable_hunters_tonic",
    "description": "Mythic refinement of Hunter's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "emberwake_tonic",
    "itemCode": "consumable_emberwake_tonic_d1",
    "displayName": "Potent Emberwake Tonic",
    "type": "tonic",
    "family": "offense",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "emberwake",
    "distillTier": "d1",
    "legacyReplaces": [
      "Emberwake Draft"
    ],
    "iconKey": "consumable_emberwake_tonic",
    "description": "Potent refinement of Emberwake Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1500
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "emberwake_tonic",
    "itemCode": "consumable_emberwake_tonic_d2",
    "displayName": "Mythic Emberwake Tonic",
    "type": "tonic",
    "family": "offense",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "emberwake",
    "distillTier": "d2",
    "legacyReplaces": [
      "Emberwake Draft"
    ],
    "iconKey": "consumable_emberwake_tonic",
    "description": "Mythic refinement of Emberwake Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1500
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "berserkers_tonic",
    "itemCode": "consumable_berserkers_tonic_d1",
    "displayName": "Potent Berserker's Tonic",
    "type": "tonic",
    "family": "frenzy",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "berserkers",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_berserkers_tonic",
    "description": "Potent refinement of Berserker's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "berserkers_tonic",
    "itemCode": "consumable_berserkers_tonic_d2",
    "displayName": "Mythic Berserker's Tonic",
    "type": "tonic",
    "family": "frenzy",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "berserkers",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_berserkers_tonic",
    "description": "Mythic refinement of Berserker's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 800
      }
    ]
  },
  {
    "consumableId": "bulwark_tonic",
    "itemCode": "consumable_bulwark_tonic_d1",
    "displayName": "Potent Bulwark Tonic",
    "type": "tonic",
    "family": "bulwark",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "bulwark",
    "distillTier": "d1",
    "legacyReplaces": [
      "Bulwark Distillate"
    ],
    "iconKey": "consumable_bulwark_tonic",
    "description": "Potent refinement of Bulwark Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1800
      },
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "bulwark_tonic",
    "itemCode": "consumable_bulwark_tonic_d2",
    "displayName": "Mythic Bulwark Tonic",
    "type": "tonic",
    "family": "bulwark",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "bulwark",
    "distillTier": "d2",
    "legacyReplaces": [
      "Bulwark Distillate"
    ],
    "iconKey": "consumable_bulwark_tonic",
    "description": "Mythic refinement of Bulwark Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "armor",
        "value": 1800
      },
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "wardwash_tonic",
    "itemCode": "consumable_wardwash_tonic_d1",
    "displayName": "Potent Wardwash Tonic",
    "type": "tonic",
    "family": "warding",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardwash",
    "distillTier": "d1",
    "legacyReplaces": [
      "Wardwash Tonic"
    ],
    "iconKey": "consumable_wardwash_tonic",
    "description": "Potent refinement of Wardwash Tonic.",
    "effects": [
      {
        "type": "affliction_resist_bps",
        "value": 3000
      },
      {
        "type": "stat_bps",
        "target": "magicDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "wardwash_tonic",
    "itemCode": "consumable_wardwash_tonic_d2",
    "displayName": "Mythic Wardwash Tonic",
    "type": "tonic",
    "family": "warding",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "wardwash",
    "distillTier": "d2",
    "legacyReplaces": [
      "Wardwash Tonic"
    ],
    "iconKey": "consumable_wardwash_tonic",
    "description": "Mythic refinement of Wardwash Tonic.",
    "effects": [
      {
        "type": "affliction_resist_bps",
        "value": 3000
      },
      {
        "type": "stat_bps",
        "target": "magicDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "hexcleanse_tonic",
    "itemCode": "consumable_hexcleanse_tonic_d1",
    "displayName": "Potent Hexcleanse Tonic",
    "type": "tonic",
    "family": "cleansing",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hexcleanse",
    "distillTier": "d1",
    "legacyReplaces": [
      "Hexcleanse Phial"
    ],
    "iconKey": "consumable_hexcleanse_tonic",
    "description": "Potent refinement of Hexcleanse Tonic.",
    "effects": [
      {
        "type": "clear_affliction",
        "target": "single",
        "value": 1
      },
      {
        "type": "affliction_resist_bps",
        "value": 5000
      }
    ]
  },
  {
    "consumableId": "hexcleanse_tonic",
    "itemCode": "consumable_hexcleanse_tonic_d2",
    "displayName": "Mythic Hexcleanse Tonic",
    "type": "tonic",
    "family": "cleansing",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "hexcleanse",
    "distillTier": "d2",
    "legacyReplaces": [
      "Hexcleanse Phial"
    ],
    "iconKey": "consumable_hexcleanse_tonic",
    "description": "Mythic refinement of Hexcleanse Tonic.",
    "effects": [
      {
        "type": "clear_affliction",
        "target": "single",
        "value": 1
      },
      {
        "type": "affliction_resist_bps",
        "value": 5000
      }
    ]
  },
  {
    "consumableId": "ravagers_tonic",
    "itemCode": "consumable_ravagers_tonic_d1",
    "displayName": "Potent Ravager's Tonic",
    "type": "tonic",
    "family": "momentum",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "ravagers",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_ravagers_tonic",
    "description": "Potent refinement of Ravager's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_flat",
        "target": "initiative",
        "value": 6
      }
    ]
  },
  {
    "consumableId": "ravagers_tonic",
    "itemCode": "consumable_ravagers_tonic_d2",
    "displayName": "Mythic Ravager's Tonic",
    "type": "tonic",
    "family": "momentum",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "encounters",
    "durationValue": 3,
    "distillGroup": "ravagers",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_ravagers_tonic",
    "description": "Mythic refinement of Ravager's Tonic.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_flat",
        "target": "initiative",
        "value": 6
      }
    ]
  },
  {
    "consumableId": "sunspike_elixir",
    "itemCode": "consumable_sunspike_elixir_d1",
    "displayName": "Potent Sunspike Elixir",
    "type": "elixir",
    "family": "offense",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "sunspike",
    "distillTier": "d1",
    "legacyReplaces": [
      "Sunspike Elixir"
    ],
    "iconKey": "consumable_sunspike_elixir",
    "description": "Potent refinement of Sunspike Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "sunspike_elixir",
    "itemCode": "consumable_sunspike_elixir_d2",
    "displayName": "Mythic Sunspike Elixir",
    "type": "elixir",
    "family": "offense",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "sunspike",
    "distillTier": "d2",
    "legacyReplaces": [
      "Sunspike Elixir"
    ],
    "iconKey": "consumable_sunspike_elixir",
    "description": "Mythic refinement of Sunspike Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 1200
      },
      {
        "type": "stat_bps",
        "target": "critMultiplier",
        "value": 1500
      }
    ]
  },
  {
    "consumableId": "graveward_elixir",
    "itemCode": "consumable_graveward_elixir_d1",
    "displayName": "Potent Graveward Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "graveward",
    "distillTier": "d1",
    "legacyReplaces": [
      "Graveward Elixir"
    ],
    "iconKey": "consumable_graveward_elixir",
    "description": "Potent refinement of Graveward Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "graveward_elixir",
    "itemCode": "consumable_graveward_elixir_d2",
    "displayName": "Mythic Graveward Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "graveward",
    "distillTier": "d2",
    "legacyReplaces": [
      "Graveward Elixir"
    ],
    "iconKey": "consumable_graveward_elixir",
    "description": "Mythic refinement of Graveward Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "maxHitpoints",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "physicalDefense",
        "value": 1200
      }
    ]
  },
  {
    "consumableId": "wardens_challenge_elixir",
    "itemCode": "consumable_wardens_challenge_elixir_d1",
    "displayName": "Potent Warden's Challenge Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "wardens_challenge",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_wardens_challenge_elixir",
    "description": "Potent refinement of Warden's Challenge Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": 2400
      }
    ]
  },
  {
    "consumableId": "wardens_challenge_elixir",
    "itemCode": "consumable_wardens_challenge_elixir_d2",
    "displayName": "Mythic Warden's Challenge Elixir",
    "type": "elixir",
    "family": "bulwark",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "wardens_challenge",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_wardens_challenge_elixir",
    "description": "Mythic refinement of Warden's Challenge Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": 3000
      }
    ]
  },
  {
    "consumableId": "shadowveil_elixir",
    "itemCode": "consumable_shadowveil_elixir_d1",
    "displayName": "Potent Shadowveil Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "shadowveil",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_shadowveil_elixir",
    "description": "Potent refinement of Shadowveil Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": -2400
      }
    ]
  },
  {
    "consumableId": "shadowveil_elixir",
    "itemCode": "consumable_shadowveil_elixir_d2",
    "displayName": "Mythic Shadowveil Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "shadowveil",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_shadowveil_elixir",
    "description": "Mythic refinement of Shadowveil Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "threat",
        "value": -3000
      }
    ]
  },
  {
    "consumableId": "deadeye_elixir",
    "itemCode": "consumable_deadeye_elixir_d1",
    "displayName": "Potent Deadeye Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "deadeye",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_deadeye_elixir",
    "description": "Potent refinement of Deadeye Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "deadeye_elixir",
    "itemCode": "consumable_deadeye_elixir_d2",
    "displayName": "Mythic Deadeye Elixir",
    "type": "elixir",
    "family": "precision",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "deadeye",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_deadeye_elixir",
    "description": "Mythic refinement of Deadeye Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "accuracy",
        "value": 1000
      },
      {
        "type": "stat_bps",
        "target": "critChance",
        "value": 1000
      }
    ]
  },
  {
    "consumableId": "travelers_elixir",
    "itemCode": "consumable_travelers_elixir_d1",
    "displayName": "Potent Traveler's Elixir",
    "type": "elixir",
    "family": "travel",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "travelers",
    "distillTier": "d1",
    "legacyReplaces": [
      "Traveler's Distillate"
    ],
    "iconKey": "consumable_travelers_elixir",
    "description": "Potent refinement of Traveler's Elixir.",
    "effects": [
      {
        "type": "contract_travel_duration_percent",
        "value": 20
      },
      {
        "type": "contract_stamina_cost_percent",
        "value": 10
      }
    ]
  },
  {
    "consumableId": "travelers_elixir",
    "itemCode": "consumable_travelers_elixir_d2",
    "displayName": "Mythic Traveler's Elixir",
    "type": "elixir",
    "family": "travel",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "travelers",
    "distillTier": "d2",
    "legacyReplaces": [
      "Traveler's Distillate"
    ],
    "iconKey": "consumable_travelers_elixir",
    "description": "Mythic refinement of Traveler's Elixir.",
    "effects": [
      {
        "type": "contract_travel_duration_percent",
        "value": 20
      },
      {
        "type": "contract_stamina_cost_percent",
        "value": 10
      }
    ]
  },
  {
    "consumableId": "contractors_resolve_elixir",
    "itemCode": "consumable_contractors_resolve_elixir_d1",
    "displayName": "Potent Contractor's Resolve Elixir",
    "type": "elixir",
    "family": "wealth",
    "rarity": "rare",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "contractors_resolve",
    "distillTier": "d1",
    "legacyReplaces": [
      "Contractor's Resolve"
    ],
    "iconKey": "consumable_contractors_resolve_elixir",
    "description": "Potent refinement of Contractor's Resolve Elixir.",
    "effects": [
      {
        "type": "contract_ducats_percent",
        "value": 15
      },
      {
        "type": "contract_item_drop_bps",
        "value": 100
      }
    ]
  },
  {
    "consumableId": "contractors_resolve_elixir",
    "itemCode": "consumable_contractors_resolve_elixir_d2",
    "displayName": "Mythic Contractor's Resolve Elixir",
    "type": "elixir",
    "family": "wealth",
    "rarity": "epic",
    "unlockBand": "medium",
    "craftingTier": "t2",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "contractors_resolve",
    "distillTier": "d2",
    "legacyReplaces": [
      "Contractor's Resolve"
    ],
    "iconKey": "consumable_contractors_resolve_elixir",
    "description": "Mythic refinement of Contractor's Resolve Elixir.",
    "effects": [
      {
        "type": "contract_ducats_percent",
        "value": 15
      },
      {
        "type": "contract_item_drop_bps",
        "value": 100
      }
    ]
  },
  {
    "consumableId": "chroniclers_elixir",
    "itemCode": "consumable_chroniclers_elixir_d1",
    "displayName": "Potent Chronicler's Elixir",
    "type": "elixir",
    "family": "experience",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "chroniclers",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_chroniclers_elixir",
    "description": "Potent refinement of Chronicler's Elixir.",
    "effects": [
      {
        "type": "contract_xp_percent",
        "value": 20
      }
    ]
  },
  {
    "consumableId": "chroniclers_elixir",
    "itemCode": "consumable_chroniclers_elixir_d2",
    "displayName": "Mythic Chronicler's Elixir",
    "type": "elixir",
    "family": "experience",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "chroniclers",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_chroniclers_elixir",
    "description": "Mythic refinement of Chronicler's Elixir.",
    "effects": [
      {
        "type": "contract_xp_percent",
        "value": 20
      }
    ]
  },
  {
    "consumableId": "warcallers_elixir",
    "itemCode": "consumable_warcallers_elixir_d1",
    "displayName": "Potent Warcaller's Elixir",
    "type": "elixir",
    "family": "frenzy",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "warcallers",
    "distillTier": "d1",
    "legacyReplaces": [],
    "iconKey": "consumable_warcallers_elixir",
    "description": "Potent refinement of Warcaller's Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 800
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 600
      }
    ]
  },
  {
    "consumableId": "warcallers_elixir",
    "itemCode": "consumable_warcallers_elixir_d2",
    "displayName": "Mythic Warcaller's Elixir",
    "type": "elixir",
    "family": "frenzy",
    "rarity": "epic",
    "unlockBand": "hard",
    "craftingTier": "t3",
    "durationKind": "hours",
    "durationValue": 8,
    "distillGroup": "warcallers",
    "distillTier": "d2",
    "legacyReplaces": [],
    "iconKey": "consumable_warcallers_elixir",
    "description": "Mythic refinement of Warcaller's Elixir.",
    "effects": [
      {
        "type": "stat_bps",
        "target": "damage",
        "value": 800
      },
      {
        "type": "stat_bps",
        "target": "extraAttackChance",
        "value": 600
      }
    ]
  }
] as const;

export const GENERATED_CONSUMABLE_RECIPES = [
  {
    "recipeId": "craft_consumable_healing_potion",
    "recipeKind": "craft",
    "outputConsumableId": "healing_potion",
    "outputTier": "base",
    "outputItemCode": "consumable_healing_potion",
    "outputRarity": "common",
    "outputCraftingTier": "t1",
    "ducatCost": 250,
    "craftingTimeSec": 300,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "ingredient_bloodleaf",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_fenroot",
        "quantity": 1
      },
      {
        "itemCode": "reagent_binder_salts",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_second_wind_potion",
    "recipeKind": "craft",
    "outputConsumableId": "second_wind_potion",
    "outputTier": "base",
    "outputItemCode": "consumable_second_wind_potion",
    "outputRarity": "common",
    "outputCraftingTier": "t1",
    "ducatCost": 300,
    "craftingTimeSec": 600,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "ingredient_fenroot",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "reagent_binder_salts",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_wardens_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "wardens_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_wardens_tonic",
    "outputRarity": "common",
    "outputCraftingTier": "t1",
    "ducatCost": 450,
    "craftingTimeSec": 900,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_bloodleaf",
        "quantity": 1
      },
      {
        "itemCode": "reagent_binder_salts",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_hunters_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "hunters_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_hunters_tonic",
    "outputRarity": "common",
    "outputCraftingTier": "t1",
    "ducatCost": 450,
    "craftingTimeSec": 900,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "reagent_binder_salts",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_emberwake_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "emberwake_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_emberwake_tonic",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 900,
    "craftingTimeSec": 1800,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_emberbud",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_berserkers_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "berserkers_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_berserkers_tonic",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1000,
    "craftingTimeSec": 1800,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_emberbud",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_bulwark_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "bulwark_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_bulwark_tonic",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1100,
    "craftingTimeSec": 2400,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_wardwash_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "wardwash_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_wardwash_tonic",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1100,
    "craftingTimeSec": 2400,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_travelers_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "travelers_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_travelers_elixir",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1300,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_fenroot",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_deadeye_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "deadeye_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_deadeye_elixir",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1400,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_wardens_challenge_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "wardens_challenge_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_wardens_challenge_elixir",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1500,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_shadowveil_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "shadowveil_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_shadowveil_elixir",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1500,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_duskmint",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_contractors_resolve_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "contractors_resolve_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_contractors_resolve_elixir",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t2",
    "ducatCost": 1500,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "ingredient_kingsfoil",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_emberbud",
        "quantity": 1
      },
      {
        "itemCode": "reagent_ward_resin",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_sunspike_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "sunspike_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_sunspike_elixir",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 2500,
    "craftingTimeSec": 7200,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_emberbud",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_sunspike",
        "quantity": 1
      },
      {
        "itemCode": "reagent_aether_catalyst",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_graveward_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "graveward_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_graveward_elixir",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 2600,
    "craftingTimeSec": 7200,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_ironbloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_gravebloom",
        "quantity": 1
      },
      {
        "itemCode": "reagent_black_ichor",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_ravagers_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "ravagers_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_ravagers_tonic",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 3000,
    "craftingTimeSec": 7200,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_sunspike",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_gravebloom",
        "quantity": 1
      },
      {
        "itemCode": "reagent_black_ichor",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_hexcleanse_tonic",
    "recipeKind": "craft",
    "outputConsumableId": "hexcleanse_tonic",
    "outputTier": "base",
    "outputItemCode": "consumable_hexcleanse_tonic",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 3200,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_shadecap",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_gravebloom",
        "quantity": 1
      },
      {
        "itemCode": "reagent_black_ichor",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_warcallers_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "warcallers_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_warcallers_elixir",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 3600,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_gravebloom",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_sunspike",
        "quantity": 1
      },
      {
        "itemCode": "reagent_aether_catalyst",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "craft_consumable_chroniclers_elixir",
    "recipeKind": "craft",
    "outputConsumableId": "chroniclers_elixir",
    "outputTier": "base",
    "outputItemCode": "consumable_chroniclers_elixir",
    "outputRarity": "rare",
    "outputCraftingTier": "t3",
    "ducatCost": 4000,
    "craftingTimeSec": 14400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "ingredient_shadecap",
        "quantity": 1
      },
      {
        "itemCode": "ingredient_sunspike",
        "quantity": 1
      },
      {
        "itemCode": "reagent_aether_catalyst",
        "quantity": 1
      }
    ]
  },
  {
    "recipeId": "distill_consumable_healing_potion_d1",
    "recipeKind": "distill",
    "outputConsumableId": "healing_potion",
    "outputTier": "d1",
    "outputItemCode": "consumable_healing_potion_d1",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 2700,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_healing_potion",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_healing_potion_d2",
    "recipeKind": "distill",
    "outputConsumableId": "healing_potion",
    "outputTier": "d2",
    "outputItemCode": "consumable_healing_potion_d2",
    "outputRarity": "rare",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_healing_potion_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_second_wind_potion_d1",
    "recipeKind": "distill",
    "outputConsumableId": "second_wind_potion",
    "outputTier": "d1",
    "outputItemCode": "consumable_second_wind_potion_d1",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 2700,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_second_wind_potion",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_second_wind_potion_d2",
    "recipeKind": "distill",
    "outputConsumableId": "second_wind_potion",
    "outputTier": "d2",
    "outputItemCode": "consumable_second_wind_potion_d2",
    "outputRarity": "rare",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_second_wind_potion_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardens_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "wardens_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_wardens_tonic_d1",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 2700,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_wardens_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardens_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "wardens_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_wardens_tonic_d2",
    "outputRarity": "rare",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_wardens_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_hunters_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "hunters_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_hunters_tonic_d1",
    "outputRarity": "uncommon",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 2700,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_hunters_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_hunters_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "hunters_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_hunters_tonic_d2",
    "outputRarity": "rare",
    "outputCraftingTier": "t1",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 1,
    "ingredients": [
      {
        "itemCode": "consumable_hunters_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_emberwake_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "emberwake_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_emberwake_tonic_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_emberwake_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_emberwake_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "emberwake_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_emberwake_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_emberwake_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_berserkers_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "berserkers_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_berserkers_tonic_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_berserkers_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_berserkers_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "berserkers_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_berserkers_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_berserkers_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_bulwark_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "bulwark_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_bulwark_tonic_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_bulwark_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_bulwark_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "bulwark_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_bulwark_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_bulwark_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardwash_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "wardwash_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_wardwash_tonic_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 3600,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_wardwash_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardwash_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "wardwash_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_wardwash_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_wardwash_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_hexcleanse_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "hexcleanse_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_hexcleanse_tonic_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 5400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_hexcleanse_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_hexcleanse_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "hexcleanse_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_hexcleanse_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_hexcleanse_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_sunspike_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "sunspike_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_sunspike_elixir_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 5400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_sunspike_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_sunspike_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "sunspike_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_sunspike_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_sunspike_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_graveward_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "graveward_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_graveward_elixir_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 5400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_graveward_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_graveward_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "graveward_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_graveward_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_graveward_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_deadeye_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "deadeye_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_deadeye_elixir_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 4500,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_deadeye_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_deadeye_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "deadeye_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_deadeye_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_deadeye_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardens_challenge_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "wardens_challenge_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_wardens_challenge_elixir_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 4500,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_wardens_challenge_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_wardens_challenge_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "wardens_challenge_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_wardens_challenge_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_wardens_challenge_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_shadowveil_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "shadowveil_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_shadowveil_elixir_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 4500,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_shadowveil_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_shadowveil_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "shadowveil_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_shadowveil_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_shadowveil_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_travelers_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "travelers_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_travelers_elixir_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 4500,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_travelers_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_travelers_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "travelers_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_travelers_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_travelers_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_contractors_resolve_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "contractors_resolve_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_contractors_resolve_elixir_d1",
    "outputRarity": "rare",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 4500,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_contractors_resolve_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_contractors_resolve_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "contractors_resolve_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_contractors_resolve_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t2",
    "ducatCost": 0,
    "craftingTimeSec": 9000,
    "requiredLevel": 15,
    "ingredients": [
      {
        "itemCode": "consumable_contractors_resolve_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_chroniclers_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "chroniclers_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_chroniclers_elixir_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_chroniclers_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_chroniclers_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "chroniclers_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_chroniclers_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 14400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_chroniclers_elixir_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_ravagers_tonic_d1",
    "recipeKind": "distill",
    "outputConsumableId": "ravagers_tonic",
    "outputTier": "d1",
    "outputItemCode": "consumable_ravagers_tonic_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 5400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_ravagers_tonic",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_ravagers_tonic_d2",
    "recipeKind": "distill",
    "outputConsumableId": "ravagers_tonic",
    "outputTier": "d2",
    "outputItemCode": "consumable_ravagers_tonic_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 10800,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_ravagers_tonic_d1",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_warcallers_elixir_d1",
    "recipeKind": "distill",
    "outputConsumableId": "warcallers_elixir",
    "outputTier": "d1",
    "outputItemCode": "consumable_warcallers_elixir_d1",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 7200,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_warcallers_elixir",
        "quantity": 3
      }
    ]
  },
  {
    "recipeId": "distill_consumable_warcallers_elixir_d2",
    "recipeKind": "distill",
    "outputConsumableId": "warcallers_elixir",
    "outputTier": "d2",
    "outputItemCode": "consumable_warcallers_elixir_d2",
    "outputRarity": "epic",
    "outputCraftingTier": "t3",
    "ducatCost": 0,
    "craftingTimeSec": 14400,
    "requiredLevel": 30,
    "ingredients": [
      {
        "itemCode": "consumable_warcallers_elixir_d1",
        "quantity": 3
      }
    ]
  }
] as const;
