// Auto-generated by tools/generate_garden_catalog.mjs
// Do not edit manually.

export const GARDEN_PLANT_IDS = [
  "bloodleaf",
  "fenroot",
  "ironbloom",
  "duskmint",
  "kingsfoil",
  "emberbud",
  "gravebloom",
  "shadecap",
  "sunspike"
] as const;

export const GARDEN_PLANT_CATALOG = [
  {
    "plantId": "bloodleaf",
    "displayName": "Bloodleaf",
    "rarity": "common",
    "seedItemCode": "seed_bloodleaf",
    "ingredientItemCode": "ingredient_bloodleaf",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Healing Potion",
      "Warden's Tonic"
    ]
  },
  {
    "plantId": "fenroot",
    "displayName": "Fenroot",
    "rarity": "common",
    "seedItemCode": "seed_fenroot",
    "ingredientItemCode": "ingredient_fenroot",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Healing Potion",
      "Second Wind Potion",
      "Traveler's Elixir"
    ]
  },
  {
    "plantId": "ironbloom",
    "displayName": "Ironbloom",
    "rarity": "common",
    "seedItemCode": "seed_ironbloom",
    "ingredientItemCode": "ingredient_ironbloom",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Warden's Tonic",
      "Hunter's Tonic",
      "Emberwake Tonic",
      "Bulwark Tonic"
    ]
  },
  {
    "plantId": "duskmint",
    "displayName": "Duskmint",
    "rarity": "common",
    "seedItemCode": "seed_duskmint",
    "ingredientItemCode": "ingredient_duskmint",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Second Wind Potion",
      "Hunter's Tonic",
      "Berserker's Tonic",
      "Wardwash Tonic",
      "Deadeye Elixir"
    ]
  },
  {
    "plantId": "kingsfoil",
    "displayName": "Kingsfoil",
    "rarity": "uncommon",
    "seedItemCode": "seed_kingsfoil",
    "ingredientItemCode": "ingredient_kingsfoil",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Bulwark Tonic",
      "Wardwash Tonic",
      "Deadeye Elixir",
      "Traveler's Elixir",
      "Contractor's Resolve Elixir"
    ]
  },
  {
    "plantId": "emberbud",
    "displayName": "Emberbud",
    "rarity": "uncommon",
    "seedItemCode": "seed_emberbud",
    "ingredientItemCode": "ingredient_emberbud",
    "growthSeconds": 6,
    "preBloomSeconds": 0,
    "bloomSeconds": 6,
    "postBloomSeconds": 6,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Emberwake Tonic",
      "Berserker's Tonic",
      "Contractor's Resolve Elixir",
      "Sunspike Elixir"
    ]
  },
  {
    "plantId": "gravebloom",
    "displayName": "Gravebloom",
    "rarity": "rare",
    "seedItemCode": "seed_gravebloom",
    "ingredientItemCode": "ingredient_gravebloom",
    "growthSeconds": 7,
    "preBloomSeconds": 0,
    "bloomSeconds": 7,
    "postBloomSeconds": 7,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Graveward Elixir",
      "Hexcleanse Tonic",
      "Ravager's Tonic",
      "Warcaller's Elixir"
    ]
  },
  {
    "plantId": "shadecap",
    "displayName": "Shadecap",
    "rarity": "rare",
    "seedItemCode": "seed_shadecap",
    "ingredientItemCode": "ingredient_shadecap",
    "growthSeconds": 7,
    "preBloomSeconds": 0,
    "bloomSeconds": 7,
    "postBloomSeconds": 7,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Hexcleanse Tonic",
      "Chronicler's Elixir"
    ]
  },
  {
    "plantId": "sunspike",
    "displayName": "Sunspike",
    "rarity": "rare",
    "seedItemCode": "seed_sunspike",
    "ingredientItemCode": "ingredient_sunspike",
    "growthSeconds": 8,
    "preBloomSeconds": 0,
    "bloomSeconds": 8,
    "postBloomSeconds": 8,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Sunspike Elixir",
      "Chronicler's Elixir",
      "Ravager's Tonic",
      "Warcaller's Elixir"
    ]
  }
] as const;
