// Auto-generated by tools/generate_garden_catalog.mjs
// Do not edit manually.

export const GARDEN_PLANT_IDS = [
  "bloodleaf",
  "fenroot",
  "ironbloom",
  "duskmint",
  "kingsfoil"
] as const;

export const GARDEN_PLANT_CATALOG = [
  {
    "plantId": "bloodleaf",
    "displayName": "Bloodleaf",
    "rarity": "common",
    "seedItemCode": "seed_bloodleaf",
    "ingredientItemCode": "ingredient_bloodleaf",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Field Tonic",
      "Healing Potion",
      "Warden's Draft"
    ]
  },
  {
    "plantId": "fenroot",
    "displayName": "Fenroot",
    "rarity": "common",
    "seedItemCode": "seed_fenroot",
    "ingredientItemCode": "ingredient_fenroot",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Field Tonic"
    ]
  },
  {
    "plantId": "ironbloom",
    "displayName": "Ironbloom",
    "rarity": "common",
    "seedItemCode": "seed_ironbloom",
    "ingredientItemCode": "ingredient_ironbloom",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Warden's Draft",
      "Hunter's Draft",
      "Bulwark Distillate"
    ]
  },
  {
    "plantId": "duskmint",
    "displayName": "Duskmint",
    "rarity": "common",
    "seedItemCode": "seed_duskmint",
    "ingredientItemCode": "ingredient_duskmint",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 2,
    "bloomYield": 4,
    "recipeRefs": [
      "Healing Potion",
      "Hunter's Draft",
      "Purge Philter"
    ]
  },
  {
    "plantId": "kingsfoil",
    "displayName": "Kingsfoil",
    "rarity": "uncommon",
    "seedItemCode": "seed_kingsfoil",
    "ingredientItemCode": "ingredient_kingsfoil",
    "growthSeconds": 5,
    "preBloomSeconds": 0,
    "bloomSeconds": 5,
    "postBloomSeconds": 5,
    "baseYield": 1,
    "bloomYield": 2,
    "recipeRefs": [
      "Greater Healing Potion",
      "Bulwark Distillate",
      "Wardwash Tonic",
      "Traveler's Distillate"
    ]
  }
] as const;
