#!/usr/bin/env python3
"""Build a generated item icon manifest for app mockup auto-hooking.

Scans:
  apps/web/public/assets/items/generated/**/*.png

Writes:
  apps/web/src/generated/itemArtManifest.ts
  apps/web/public/assets/items/generated/item_art_manifest.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ASSET_ROOT = REPO_ROOT / "apps" / "web" / "public" / "assets" / "items" / "generated"
DEFAULT_TS_OUT = REPO_ROOT / "apps" / "web" / "src" / "generated" / "itemArtManifest.ts"
DEFAULT_JSON_OUT = DEFAULT_ASSET_ROOT / "item_art_manifest.json"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build generated item icon manifest.")
    p.add_argument("--asset-root", default=str(DEFAULT_ASSET_ROOT))
    p.add_argument("--ts-out", default=str(DEFAULT_TS_OUT))
    p.add_argument("--json-out", default=str(DEFAULT_JSON_OUT))
    return p.parse_args()


def norm_name_from_slug(slug: str) -> str:
    return " ".join(slug.replace("-", "_").split("_")).strip().lower()


def strip_prefix(name_slug: str, expected_prefix: str) -> str:
    prefix = f"{expected_prefix}_"
    if name_slug.startswith(prefix):
        return name_slug[len(prefix) :]
    return name_slug


def key_for_path(rel: Path) -> tuple[str, str] | None:
    parts = rel.parts
    if len(parts) < 3:
        return None
    major = parts[0]
    filename = rel.stem.lower().replace("-", "_")

    if major == "weapon":
        if len(parts) < 4:
            return None
        weapon_archetype = parts[1].lower()
        family_prefix_by_arch = {
            "melee": "warrior_melee",
            "ranged": "ranger_ranged",
            "arcane": "mage_arcane",
        }
        family_prefix = family_prefix_by_arch.get(weapon_archetype, weapon_archetype)
        item_slug = strip_prefix(filename, family_prefix)
        key = f"weapon:{weapon_archetype}:{norm_name_from_slug(item_slug)}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    if major == "armor":
        if len(parts) < 4:
            return None
        armor_archetype = parts[1].lower()
        family_prefix = f"{armor_archetype}_armor"
        item_slug = strip_prefix(filename, family_prefix)
        key = f"armor:{armor_archetype}:{norm_name_from_slug(item_slug)}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    if major == "jewelry":
        if len(parts) < 3:
            return None
        jewelry_type = parts[1].lower()
        family_prefix = jewelry_type
        item_slug = strip_prefix(filename, family_prefix)
        key = f"jewelry:{jewelry_type}:{norm_name_from_slug(item_slug)}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    return None


def build_manifest(asset_root: Path) -> dict[str, str]:
    manifest: dict[str, str] = {}
    for png in sorted(asset_root.rglob("*.png")):
        rel = png.relative_to(asset_root)
        parsed = key_for_path(rel)
        if not parsed:
            continue
        key, path = parsed
        manifest[key] = path
    return manifest


def write_ts_manifest(ts_out: Path, manifest: dict[str, str]) -> None:
    ts_out.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(manifest, indent=2, ensure_ascii=True)
    content = (
        "// Auto-generated by tools/build_item_art_manifest.py\n"
        "// Do not edit manually.\n\n"
        "export const GENERATED_ITEM_ICON_PATHS: Record<string, string> = "
        f"{body};\n"
    )
    ts_out.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()
    asset_root = Path(args.asset_root)
    ts_out = Path(args.ts_out)
    json_out = Path(args.json_out)

    if not asset_root.is_absolute():
        asset_root = (REPO_ROOT / asset_root).resolve()
    if not ts_out.is_absolute():
        ts_out = (REPO_ROOT / ts_out).resolve()
    if not json_out.is_absolute():
        json_out = (REPO_ROOT / json_out).resolve()

    manifest = build_manifest(asset_root)

    write_ts_manifest(ts_out, manifest)
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Manifest entries: {len(manifest)}")
    print(f"TS manifest: {ts_out}")
    print(f"JSON manifest: {json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

