"""Build a shared guild crest catalog from crest CSV data and generated PNGs."""

from __future__ import annotations

import csv
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = REPO_ROOT / "docs" / "data" / "guild_crests_v1.csv"
ASSET_DIR = REPO_ROOT / "apps" / "web" / "public" / "assets" / "items" / "generated" / "crest" / "guild"
OUT_PATH = REPO_ROOT / "packages" / "shared" / "src" / "generated" / "guildCrestCatalog.ts"


def load_rows() -> list[dict[str, str]]:
    with CSV_PATH.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return [dict(row) for row in reader]


def build_catalog(rows: list[dict[str, str]]) -> tuple[list[dict[str, object]], list[str], list[str]]:
    catalog: list[dict[str, object]] = []
    all_ids: list[str] = []
    available_ids: list[str] = []

    for row in rows:
        crest_id = (row.get("crest_id") or "").strip()
        if not crest_id:
            continue

        icon_file = ASSET_DIR / f"{crest_id}.png"
        icon_path = f"/assets/items/generated/crest/guild/{crest_id}.png" if icon_file.exists() else None

        all_ids.append(crest_id)
        if icon_path is not None:
            available_ids.append(crest_id)

        catalog.append(
            {
                "crestId": crest_id,
                "title": (row.get("crest_title") or "").strip(),
                "backstory": (row.get("backstory") or "").strip(),
                "promptBuild": (row.get("prompt_build") or "").strip(),
                "iconPath": icon_path,
                "available": icon_path is not None,
                "artKey": f"crest:guild:{crest_id}",
            }
        )

    return catalog, all_ids, available_ids


def render_ts(catalog: list[dict[str, object]], all_ids: list[str], available_ids: list[str]) -> str:
    available_catalog = [entry for entry in catalog if entry["available"]]
    default_id = available_ids[0] if available_ids else (all_ids[0] if all_ids else "crest_0")
    catalog_json = json.dumps(catalog, indent=2, ensure_ascii=True)
    available_catalog_json = json.dumps(available_catalog, indent=2, ensure_ascii=True)
    all_ids_json = json.dumps(all_ids, ensure_ascii=True)
    available_ids_json = json.dumps(available_ids, ensure_ascii=True)

    return "\n".join(
        [
            "// Generated by tools/build_guild_crest_catalog.py",
            "// Source: docs/data/guild_crests_v1.csv + apps/web/public/assets/items/generated/crest/guild/*.png",
            "",
            "export interface GuildCrestCatalogEntry {",
            "  crestId: string;",
            "  title: string;",
            "  backstory: string;",
            "  promptBuild: string;",
            "  iconPath: string | null;",
            "  available: boolean;",
            "  artKey: string;",
            "}",
            "",
            f"export const guildCrestCatalog = {catalog_json} as const satisfies readonly GuildCrestCatalogEntry[];",
            "",
            f"export const guildCrestIds = {all_ids_json} as const;",
            f"export const availableGuildCrestIds = {available_ids_json} as const;",
            f"export const defaultGuildCrestId = {json.dumps(default_id, ensure_ascii=True)};",
            "",
            f"export const availableGuildCrestCatalog = {available_catalog_json} as const satisfies readonly GuildCrestCatalogEntry[];",
            "",
        ]
    )


def main() -> None:
    rows = load_rows()
    catalog, all_ids, available_ids = build_catalog(rows)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render_ts(catalog, all_ids, available_ids), encoding="utf-8")
    print(f"Wrote guild crest catalog: {OUT_PATH}")
    print(f"Catalog entries: {len(catalog)}")
    print(f"Available crest images: {len(available_ids)}")


if __name__ == "__main__":
    main()
