import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const csvPath = path.join(repoRoot, "docs", "data", "garden_plants_v1.csv");
const outputPath = path.join(repoRoot, "packages", "shared", "src", "domains", "garden", "catalog.generated.ts");

function parseCsvLine(line) {
  return line.split(",").map((part) => part.trim());
}

function readRows() {
  const source = readFileSync(csvPath, "utf8").trim();
  const lines = source.split(/\r?\n/).filter(Boolean);
  const headers = parseCsvLine(lines[0]);

  return lines.slice(1).map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""]));
  });
}

function buildOutput(rows) {
  const plantIds = rows.map((row) => row.plant_id);
  const catalogEntries = rows.map((row) => ({
    plantId: row.plant_id,
    displayName: row.display_name,
    rarity: row.rarity,
    seedItemCode: row.seed_item_code,
    ingredientItemCode: row.ingredient_item_code,
    growthSeconds: Number.parseInt(row.growth_seconds, 10),
    preBloomSeconds: Number.parseInt(row.pre_bloom_seconds, 10),
    bloomSeconds: Number.parseInt(row.bloom_seconds, 10),
    postBloomSeconds: Number.parseInt(row.post_bloom_seconds, 10),
    baseYield: Number.parseInt(row.base_yield, 10),
    bloomYield: Number.parseInt(row.bloom_yield, 10),
    recipeRefs: row.recipe_refs
      .split(";")
      .map((value) => value.trim())
      .filter(Boolean)
  }));

  return `// Auto-generated by tools/generate_garden_catalog.mjs
// Do not edit manually.

export const GARDEN_PLANT_IDS = ${JSON.stringify(plantIds, null, 2)} as const;

export const GARDEN_PLANT_CATALOG = ${JSON.stringify(catalogEntries, null, 2)} as const;
`;
}

const rows = readRows();
mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, buildOutput(rows), "utf8");
console.log(`Wrote ${path.relative(repoRoot, outputPath)}`);
