#!/usr/bin/env python3
"""Generate item art assets from docs/data CSV definitions via OpenAI Images API.

Behavior:
- One item per API request.
- Prompt layering: general + family + item-specific fields.
- Hash-aware reruns: skip unchanged existing files.
- Missing/empty `prompt_item_description` rows are skipped.
"""

from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import json
import os
import random
import re
import ssl
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib import error, request


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG_PATH = REPO_ROOT / "tools" / "item_art_prompts.yaml"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "apps" / "web" / "public" / "assets" / "items" / "generated"
DEFAULT_CACHE_DIR = REPO_ROOT / "tools" / ".cache"
DEFAULT_STATE_PATH = DEFAULT_CACHE_DIR / "item_art_state.json"
DEFAULT_REPORT_PATH = DEFAULT_CACHE_DIR / "item_art_last_run.json"
DEFAULT_ENV_PATH = REPO_ROOT / ".env"
DEFAULT_MANIFEST_TS_PATH = REPO_ROOT / "apps" / "web" / "src" / "generated" / "itemArtManifest.ts"
DEFAULT_MANIFEST_JSON_PATH = REPO_ROOT / "apps" / "web" / "public" / "assets" / "items" / "generated" / "item_art_manifest.json"

TRANSIENT_STATUS_CODES = {429, 500, 502, 503, 504}


def key_for_generated_asset(rel: Path) -> tuple[str, str] | None:
    parts = rel.parts
    if len(parts) < 3:
        return None
    major = parts[0]
    filename = rel.stem.lower().replace("-", "_")

    if major == "weapon":
        if len(parts) < 4:
            return None
        weapon_archetype = parts[1].lower()
        family_prefix_by_arch = {
            "melee": "warrior_melee",
            "ranged": "ranger_ranged",
            "arcane": "mage_arcane",
        }
        family_prefix = family_prefix_by_arch.get(weapon_archetype, weapon_archetype)
        prefix = f"{family_prefix}_"
        item_slug = filename[len(prefix) :] if filename.startswith(prefix) else filename
        item_name_norm = " ".join(item_slug.split("_")).strip().lower()
        key = f"weapon:{weapon_archetype}:{item_name_norm}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    if major == "armor":
        if len(parts) < 4:
            return None
        armor_archetype = parts[1].lower()
        family_prefix = f"{armor_archetype}_armor_"
        item_slug = filename[len(family_prefix) :] if filename.startswith(family_prefix) else filename
        item_name_norm = " ".join(item_slug.split("_")).strip().lower()
        key = f"armor:{armor_archetype}:{item_name_norm}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    if major == "jewelry":
        if len(parts) < 3:
            return None
        jewelry_type = parts[1].lower()
        family_prefix = f"{jewelry_type}_"
        item_slug = filename[len(family_prefix) :] if filename.startswith(family_prefix) else filename
        item_name_norm = " ".join(item_slug.split("_")).strip().lower()
        key = f"jewelry:{jewelry_type}:{item_name_norm}"
        return key, f"/assets/items/generated/{rel.as_posix()}"

    return None


def write_generated_item_manifest(output_dir: Path) -> None:
    manifest: dict[str, str] = {}
    for png in sorted(output_dir.rglob("*.png")):
        rel = png.relative_to(output_dir)
        parsed = key_for_generated_asset(rel)
        if not parsed:
            continue
        key, asset_path = parsed
        manifest[key] = asset_path

    DEFAULT_MANIFEST_TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts_body = json.dumps(manifest, indent=2, ensure_ascii=True)
    DEFAULT_MANIFEST_TS_PATH.write_text(
        "// Auto-generated by tools/generate_item_art.py\n"
        "// Do not edit manually.\n\n"
        "export const GENERATED_ITEM_ICON_PATHS: Record<string, string> = "
        f"{ts_body};\n",
        encoding="utf-8",
    )

    DEFAULT_MANIFEST_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    DEFAULT_MANIFEST_JSON_PATH.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


@dataclass
class ItemRecord:
    item_id: str
    source_id: str
    source_group: str
    csv_path: str
    row_number: int
    major_category: str
    family_key: str
    display_name: str
    item_type: str
    base_level: int
    level_band: str
    prompt_item_description: str
    flavor_text: str


def load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def load_config(config_path: Path) -> dict[str, Any]:
    text = config_path.read_text(encoding="utf-8")
    # JSON is valid YAML 1.2 and avoids mandatory parser deps.
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text)
        if not isinstance(data, dict):
            raise ValueError("Top-level config must be an object/map.")
        return data
    except ImportError as exc:
        raise RuntimeError(
            "Config is not JSON and PyYAML is not installed. "
            "Install pyyaml or keep tools/item_art_prompts.yaml JSON-compatible."
        ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate item art assets from docs/data CSV files.")
    parser.add_argument(
        "--sources",
        choices=["all", "weapons", "armor", "jewelry"],
        default="all",
        help="Subset of configured sources to process.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Output directory for generated PNG assets.",
    )
    parser.add_argument("--limit", type=int, default=None, help="Process at most N eligible items.")
    parser.add_argument("--dry-run", action="store_true", help="Plan actions only; do not call API or write PNG files.")
    parser.add_argument("--force", action="store_true", help="Regenerate all selected eligible items.")
    parser.add_argument(
        "--only-missing",
        action="store_true",
        help="Only generate if image file is missing; ignore hash changes.",
    )
    parser.add_argument("--verbose", action="store_true", help="Verbose per-item logging.")
    parser.add_argument(
        "--random-level-sample",
        action="store_true",
        help="Sample planned items randomly across low/mid/high level bands before applying --limit.",
    )
    parser.add_argument(
        "--random-seed",
        type=int,
        default=None,
        help="Optional seed for deterministic random sampling order.",
    )
    parser.add_argument("--config", default=str(DEFAULT_CONFIG_PATH), help="Path to prompt/source YAML config.")
    parser.add_argument(
        "--ca-bundle",
        default=None,
        help="Path to a PEM CA bundle for TLS verification (optional).",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Disable TLS certificate verification (only for local troubleshooting).",
    )
    return parser.parse_args()


def read_csv_rows(csv_path: Path) -> list[dict[str, str]]:
    encodings = ["utf-8-sig", "utf-8", "cp1252", "latin-1"]
    last_error: Exception | None = None
    for encoding in encodings:
        try:
            with csv_path.open("r", encoding=encoding, newline="") as handle:
                return list(csv.DictReader(handle))
        except UnicodeDecodeError as exc:
            last_error = exc
    if last_error is not None:
        raise last_error
    return []


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug or "item"


def slugify_underscore(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.lower()).strip("_")
    return slug or "item"


def asset_family_for(record: ItemRecord) -> str:
    if record.major_category == "armor":
        parts = record.family_key.split(":")
        archetype = parts[1] if len(parts) > 1 else "armor"
        return f"{slugify_underscore(archetype)}_armor"

    if record.major_category == "jewelry":
        parts = record.family_key.split(":")
        archetype = parts[1] if len(parts) > 1 else "jewelry"
        return slugify_underscore(archetype)

    if record.major_category == "weapon":
        # Source ids are curated and stable, use them as the naming family,
        # stripping version/manual suffixes for readability.
        family = slugify_underscore(record.source_id)
        family = re.sub(r"_v\d+_manual$", "", family)
        family = re.sub(r"_v\d+$", "", family)
        family = re.sub(r"_manual$", "", family)
        return family

    return slugify_underscore(record.major_category)


def output_filename_for(record: ItemRecord) -> str:
    family = asset_family_for(record)
    name = slugify_underscore(record.display_name)
    return f"{family}_{name}.png"


def level_band(base_level: int) -> str:
    if base_level <= 16:
        return "low"
    if base_level <= 64:
        return "mid"
    return "high"


def infer_major_category(source: dict[str, Any], row: dict[str, str]) -> str:
    if source.get("major_category"):
        return str(source["major_category"])
    if "weapon_family" in row:
        return "weapon"
    if row.get("major_category"):
        return row["major_category"]
    return "item"


def build_family_key(source: dict[str, Any], row: dict[str, str], major_category: str) -> str:
    if source.get("family_key_template"):
        template = str(source["family_key_template"])
        return template.format(**{k: (v or "") for k, v in row.items()})

    if major_category == "weapon":
        return f"weapon:{row.get('weapon_family', '').strip()}:{row.get('weapon_type', '').strip().lower()}"
    if major_category == "armor":
        return f"armor:{row.get('archetype', '').strip()}:{row.get('slot_family', '').strip()}"
    if major_category == "jewelry":
        return f"jewelry:{row.get('archetype', '').strip()}"
    return major_category


def build_item_record(source: dict[str, Any], row: dict[str, str], row_idx: int) -> ItemRecord | None:
    major = infer_major_category(source, row)

    sequence_raw = (row.get("sequence") or "").strip() or str(row_idx)
    try:
        sequence_int = int(sequence_raw)
    except ValueError:
        sequence_int = row_idx

    if major == "weapon":
        display_name = (row.get("weapon_name") or "").strip()
        item_type = (row.get("weapon_type") or "").strip()
    else:
        display_name = (row.get("item_name") or "").strip()
        item_type = (row.get("item_type") or "").strip()

    base_level_raw = (row.get("base_level") or "0").strip()
    try:
        base_level_int = int(base_level_raw)
    except ValueError:
        base_level_int = 0

    prompt_desc = (row.get("prompt_item_description") or "").strip()
    if not prompt_desc:
        return None

    family_key = build_family_key(source, row, major)
    source_id = str(source["id"])
    item_id = f"{source_id}_{sequence_int:03d}_{slugify(display_name)}"

    return ItemRecord(
        item_id=item_id,
        source_id=source_id,
        source_group=str(source.get("group", "other")),
        csv_path=str(source["path"]),
        row_number=row_idx,
        major_category=major,
        family_key=family_key,
        display_name=display_name,
        item_type=item_type,
        base_level=base_level_int,
        level_band=level_band(base_level_int),
        prompt_item_description=prompt_desc,
        flavor_text=(row.get("flavor_text") or "").strip(),
    )


def compose_prompt(record: ItemRecord, config: dict[str, Any]) -> str:
    general_prompt = str(config.get("general_prompt", "")).strip()
    family_prompts = config.get("families", {})
    family_prompt = str(family_prompts.get(record.family_key, "")).strip()
    if record.major_category == "weapon":
        design_block = f"Weapon Design:\n\n{record.prompt_item_description.strip()}"
    else:
        design_block = record.prompt_item_description.strip()
    identity_block = (
        f'image should represent well an item with name "{record.display_name}" '
        f'with this flavor description: {record.flavor_text}'
    ).strip()

    blocks = [
        general_prompt,
        family_prompt,
        design_block,
        identity_block,
    ]
    return "\n\n".join(block for block in blocks if block)


def compute_prompt_hash(model: str, size: str, background: str, quality: str, prompt: str, item_id: str) -> str:
    payload = {
        "model": model,
        "size": size,
        "background": background,
        "quality": quality,
        "prompt": prompt,
        "item_id": item_id,
    }
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=True).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def call_openai_image(
    *,
    api_key: str,
    base_url: str,
    model: str,
    prompt: str,
    size: str,
    background: str,
    quality: str,
    ssl_context: ssl.SSLContext,
    max_attempts: int = 5,
    timeout_seconds: int = 180,
) -> bytes:
    endpoint = f"{base_url.rstrip('/')}/v1/images/generations"
    payload = {
        "model": model,
        "prompt": prompt,
        "size": size,
        "background": background,
        "quality": quality,
        "output_format": "png",
        "n": 1,
    }

    raw_body = json.dumps(payload).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    for attempt in range(1, max_attempts + 1):
        req = request.Request(endpoint, data=raw_body, headers=headers, method="POST")
        try:
            with request.urlopen(req, timeout=timeout_seconds, context=ssl_context) as resp:
                response_body = resp.read().decode("utf-8")
            parsed = json.loads(response_body)
            data = parsed.get("data")
            if not isinstance(data, list) or not data:
                raise RuntimeError(f"OpenAI response missing image data: {response_body[:400]}")
            entry = data[0]
            if "b64_json" in entry and entry["b64_json"]:
                return base64.b64decode(entry["b64_json"])
            if "url" in entry and entry["url"]:
                with request.urlopen(entry["url"], timeout=timeout_seconds, context=ssl_context) as image_resp:
                    return image_resp.read()
            raise RuntimeError(f"OpenAI response missing b64_json/url: {response_body[:400]}")
        except error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            if exc.code in TRANSIENT_STATUS_CODES and attempt < max_attempts:
                time.sleep(2 ** (attempt - 1))
                continue
            raise RuntimeError(f"OpenAI HTTP {exc.code}: {body[:500]}") from exc
        except error.URLError as exc:
            if attempt < max_attempts:
                time.sleep(2 ** (attempt - 1))
                continue
            raise RuntimeError(f"OpenAI network error: {exc}") from exc

    raise RuntimeError("Image generation failed after retries.")


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def save_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def should_include_source(source_group: str, selected: str) -> bool:
    if selected == "all":
        return True
    return source_group == selected


def build_ssl_context(*, insecure: bool, ca_bundle: str | None) -> ssl.SSLContext:
    if insecure:
        return ssl._create_unverified_context()  # noqa: SLF001

    cafile = (ca_bundle or "").strip()
    if cafile:
        return ssl.create_default_context(cafile=cafile)

    # Try certifi first for Windows environments with missing Python cert store.
    try:
        import certifi  # type: ignore

        return ssl.create_default_context(cafile=certifi.where())
    except Exception:
        return ssl.create_default_context()


def main() -> int:
    args = parse_args()
    load_dotenv(DEFAULT_ENV_PATH)

    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = (REPO_ROOT / config_path).resolve()
    if not config_path.exists():
        print(f"Config file not found: {config_path}", file=sys.stderr)
        return 2

    config = load_config(config_path)

    sources = config.get("sources")
    if not isinstance(sources, list):
        print("Config error: 'sources' must be a list.", file=sys.stderr)
        return 2

    render_defaults = config.get("render_defaults", {})
    model = str(render_defaults.get("model", "gpt-image-1"))
    size = str(render_defaults.get("size", "1024x1024"))
    background = str(render_defaults.get("background", "transparent"))
    quality = str(render_defaults.get("quality", "low"))
    base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com")
    api_key = os.environ.get("OPENAI_API_KEY", "")
    env_ca_bundle = os.environ.get("OPENAI_CA_BUNDLE", "").strip()
    cli_ca_bundle = (args.ca_bundle or "").strip()
    ca_bundle = cli_ca_bundle or env_ca_bundle or None
    ssl_context = build_ssl_context(insecure=args.insecure, ca_bundle=ca_bundle)

    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = (REPO_ROOT / output_dir).resolve()

    state = load_json(DEFAULT_STATE_PATH)
    state_items = state.get("items") if isinstance(state.get("items"), dict) else {}

    planned: list[tuple[ItemRecord, str, str, str]] = []
    counts: dict[str, int] = {
        "total_rows": 0,
        "eligible_rows": 0,
        "skipped_missing_prompt": 0,
        "skipped_source_filter": 0,
        "skipped_family_prompt": 0,
        "skipped_unchanged": 0,
        "generated": 0,
        "regenerated": 0,
        "failed": 0,
    }

    for source in sources:
        if not isinstance(source, dict):
            continue
        source_group = str(source.get("group", "other"))
        if not should_include_source(source_group, args.sources):
            counts["skipped_source_filter"] += 1
            continue
        source_path_value = source.get("path")
        source_id = source.get("id")
        if not source_path_value or not source_id:
            print(f"Config source missing id/path: {source}", file=sys.stderr)
            return 2
        csv_path = Path(str(source_path_value))
        if not csv_path.is_absolute():
            csv_path = (REPO_ROOT / csv_path).resolve()
        if not csv_path.exists():
            print(f"CSV source not found: {csv_path}", file=sys.stderr)
            return 2

        rows = read_csv_rows(csv_path)
        for idx, row in enumerate(rows, start=1):
            counts["total_rows"] += 1
            row = {str(k): ("" if v is None else str(v)) for k, v in row.items()}
            source_copy = dict(source)
            source_copy["path"] = str(csv_path)
            record = build_item_record(source_copy, row, idx)
            if record is None:
                counts["skipped_missing_prompt"] += 1
                continue

            family_prompts = config.get("families", {})
            family_prompt = str(family_prompts.get(record.family_key, "")).strip()
            if not family_prompt:
                counts["skipped_family_prompt"] += 1
                continue

            final_prompt = compose_prompt(record, config)
            prompt_hash = compute_prompt_hash(
                model,
                size,
                background,
                quality,
                final_prompt,
                record.item_id,
            )
            # Avoid duplicated directories like armor/armor/... by dropping the family_key prefix.
            family_parts = record.family_key.split(":")
            if family_parts and family_parts[0] == record.major_category:
                family_parts = family_parts[1:]
            rel_parts = [record.major_category] + family_parts + [output_filename_for(record)]
            output_path = output_dir.joinpath(*rel_parts)

            counts["eligible_rows"] += 1
            planned.append((record, final_prompt, prompt_hash, str(output_path)))

    rng = random.Random(args.random_seed)

    if args.random_level_sample and planned:
        by_band: dict[str, list[tuple[ItemRecord, str, str, str]]] = {"low": [], "mid": [], "high": []}
        for item in planned:
            record = item[0]
            bucket = by_band.get(record.level_band)
            if bucket is not None:
                bucket.append(item)
            else:
                by_band["mid"].append(item)

        for entries in by_band.values():
            rng.shuffle(entries)

        if args.limit is not None and args.limit >= 0:
            target = args.limit
        else:
            target = len(planned)

        sampled: list[tuple[ItemRecord, str, str, str]] = []
        for band in ("low", "mid", "high"):
            if len(sampled) >= target:
                break
            if by_band[band]:
                sampled.append(by_band[band].pop())

        remaining: list[tuple[ItemRecord, str, str, str]] = by_band["low"] + by_band["mid"] + by_band["high"]
        rng.shuffle(remaining)
        if len(sampled) < target:
            sampled.extend(remaining[: target - len(sampled)])
        planned = sampled
    elif args.random_seed is not None:
        rng.shuffle(planned)

    if args.limit is not None and args.limit >= 0:
        planned = planned[: args.limit]

    if args.verbose or args.dry_run:
        print(f"Planned eligible items: {len(planned)}")

    if not args.dry_run and not api_key:
        print("OPENAI_API_KEY is required for non-dry runs.", file=sys.stderr)
        return 2

    run_items: list[dict[str, Any]] = []

    for record, final_prompt, prompt_hash, output_path_str in planned:
        output_path = Path(output_path_str)
        prompt_output_path = output_path.with_suffix(".txt")
        previous = state_items.get(record.item_id, {}) if isinstance(state_items, dict) else {}
        previous_hash = previous.get("hash") if isinstance(previous, dict) else None
        file_exists = output_path.exists()

        action = "generate"
        if args.force:
            action = "regenerate" if file_exists else "generate"
        elif args.only_missing:
            if file_exists:
                action = "skip_unchanged"
            else:
                action = "generate"
        else:
            if file_exists and previous_hash == prompt_hash:
                action = "skip_unchanged"
            elif file_exists:
                action = "regenerate"
            else:
                action = "generate"

        if action == "skip_unchanged":
            counts["skipped_unchanged"] += 1
            if not args.dry_run and file_exists and not prompt_output_path.exists():
                prompt_output_path.parent.mkdir(parents=True, exist_ok=True)
                prompt_output_path.write_text(final_prompt + "\n", encoding="utf-8")
            run_items.append(
                {
                    "item_id": record.item_id,
                    "status": "skipped_unchanged",
                    "output_path": str(output_path),
                    "prompt_path": str(prompt_output_path),
                    "family_key": record.family_key,
                }
            )
            if args.verbose:
                print(f"SKIP {record.item_id} -> {output_path}")
            continue

        if args.dry_run:
            run_items.append(
                {
                    "item_id": record.item_id,
                    "status": f"would_{action}",
                    "output_path": str(output_path),
                    "prompt_path": str(prompt_output_path),
                    "family_key": record.family_key,
                    "prompt_preview": final_prompt[:220],
                }
            )
            if args.verbose:
                print(f"DRYRUN {action.upper()} {record.item_id} -> {output_path}")
            continue

        try:
            image_bytes = call_openai_image(
                api_key=api_key,
                base_url=base_url,
                model=model,
                prompt=final_prompt,
                size=size,
                background=background,
                quality=quality,
                ssl_context=ssl_context,
            )
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_bytes(image_bytes)
            prompt_output_path.write_text(final_prompt + "\n", encoding="utf-8")

            if action == "generate":
                counts["generated"] += 1
            else:
                counts["regenerated"] += 1

            state_items[record.item_id] = {
                "hash": prompt_hash,
                "output_path": str(output_path),
                "family_key": record.family_key,
                "source_id": record.source_id,
                "updated_at": int(time.time()),
                "model": model,
                "size": size,
                "background": background,
                "quality": quality,
            }
            run_items.append(
                {
                    "item_id": record.item_id,
                    "status": action,
                    "output_path": str(output_path),
                    "prompt_path": str(prompt_output_path),
                    "family_key": record.family_key,
                }
            )
            if args.verbose:
                print(f"{action.upper()} {record.item_id} -> {output_path}")
        except Exception as exc:  # noqa: BLE001
            counts["failed"] += 1
            run_items.append(
                {
                    "item_id": record.item_id,
                    "status": "failed",
                    "error": str(exc),
                    "output_path": str(output_path),
                    "prompt_path": str(prompt_output_path),
                    "family_key": record.family_key,
                }
            )
            print(f"FAILED {record.item_id}: {exc}", file=sys.stderr)

    if not args.dry_run:
        save_json(DEFAULT_STATE_PATH, {"items": state_items})
        # Keep the app-side icon manifest in sync as assets are generated/regenerated.
        write_generated_item_manifest(output_dir)

    report = {
        "timestamp": int(time.time()),
        "config_path": str(config_path),
        "output_dir": str(output_dir),
        "sources_filter": args.sources,
        "dry_run": args.dry_run,
        "force": args.force,
        "only_missing": args.only_missing,
        "render": {
            "model": model,
            "size": size,
            "background": background,
            "quality": quality,
            "base_url": base_url,
            "tls_verify": not args.insecure,
            "ca_bundle": ca_bundle or "",
        },
        "sampling": {
            "random_level_sample": args.random_level_sample,
            "random_seed": args.random_seed,
        },
        "counts": counts,
        "items": run_items,
    }
    save_json(DEFAULT_REPORT_PATH, report)

    print(json.dumps({"counts": counts, "report_path": str(DEFAULT_REPORT_PATH)}, indent=2))
    return 1 if counts["failed"] > 0 else 0


if __name__ == "__main__":
    raise SystemExit(main())
